sudo: true
services: docker
language: go
go:
- 1.12
addons:
  apt:
    packages:
    - node
env:
- DOCKER_COMPOSE_VERSION=3
install: true
branches:
  only:
  - develop
script:
- docker-compose up --build -d
before_install:
- openssl aes-256-cbc -K $encrypted_a9b69efaae82_key -iv $encrypted_a9b69efaae82_iv
  -in escapade-compose.zip.enc -out ./escapade-compose.zip -d
- base=https://github.com/docker/machine/releases/download/v0.16.0 && curl -L $base/docker-machine-$(uname
  -s)-$(uname -m) >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/local/bin/docker-machine
- npm install -g machine-share
- machine-import escapade-compose.zip
- eval $(docker-machine env escapade-compose)
- export COMPOSE_TLS_VERSION=TLSv1_2
