version: '3'
services:

  pg:
    image: smartphonejava/pg:latest
    build:
      dockerfile: Dockerfile
      context: ./../../../../extra/postgresql/main/

  pg-ery:
    image: smartphonejava/pg-ery:latest    
    build:
      dockerfile: Dockerfile
      context: ./../../../../extra/postgresql/ery/  

  consul:
    image: smartphonejava/consul:latest
    build:
      dockerfile: Dockerfile
      context: ./../../../../extra/consul

  front:
    image: smartphonejava/front:latest
    build:
      dockerfile: 2019_1_Escapade/extra/front/Dockerfile
      context: ./../../../../../
