basePath: /api
definitions:
  models.Pages:
    properties:
      amount:
        type: integer
    type: object
  models.Result:
    properties:
      message:
        type: string
      place:
        type: string
      success:
        type: boolean
    type: object
  models.UserPublicInfo:
    properties:
      bestScore:
        type: string
      bestTime:
        type: string
      difficult:
        type: integer
      id:
        type: integer
      name:
        type: string
      photo:
        type: string
    type: object
host: https://explosion.team
info:
  contact: {}
  description: API documentation
  license: {}
  title: Escapade Explosion API
  version: "1.0"
paths:
  /avatar:
    get:
      description: Get user avatar
      operationId: GetImage
      responses:
        "200":
          description: Avatar found successfully
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Required authorization
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: Avatar not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Get user avatar
    post:
      description: Create user avatar
      operationId: PostImage
      responses:
        "201":
          description: Avatar created successfully
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Required authorization
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: Avatar not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Create user avatar
  /session:
    delete:
      description: logout
      operationId: Logout
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Require authorization
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: logout
    post:
      description: login
      operationId: Login
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.UserPublicInfo'
        "400":
          description: invalid name or password
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: login
  /user:
    delete:
      description: delete account
      operationId: DeleteAccount
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: invalid input
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: delete account
    get:
      description: get public information about that user
      operationId: GetMyProfile
      responses:
        "201":
          description: Create user successfully
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: Invalid information
          schema:
            $ref: '#/definitions/models.Result'
      summary: get public information about that user
    options:
      description: catch CORS preflight
      operationId: OK1
      responses:
        "200":
          description: successfully
      summary: catch CORS preflight
    post:
      description: create new user
      operationId: Register
      responses:
        "201":
          description: Create user successfully
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: Invalid information
          schema:
            $ref: '#/definitions/models.Result'
      summary: create new user
    put:
      description: update public info
      operationId: UpdateProfile
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: invalid info
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: need authorization
          schema:
            $ref: '#/definitions/models.Result'
      summary: update user information
  /users/{name}/profile:
    get:
      consumes:
      - application/json
      description: get user's best score and best time for a given difficulty, user's
        id, name and photo
      operationId: GetProfile
      parameters:
      - description: User name
        in: path
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Profile found successfully
          schema:
            $ref: '#/definitions/models.UserPublicInfo'
        "400":
          description: Invalid username
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Get public user inforamtion
  /users/{page}:
    get:
      description: Get page of user list
      operationId: GetUsers
      responses:
        "200":
          description: Get successfully
          schema:
            items:
              $ref: '#/definitions/models.Result'
            type: array
        "400":
          description: Invalid pade
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: Users not found
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: Get users list
  /users/pages_amount:
    get:
      description: Get amount of users list page
      operationId: GetUsersPageAmount
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Pages'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: amount of users list page
swagger: "2.0"
