basePath: /api
definitions:
  models.Pages:
    properties:
      amount:
        type: integer
    type: object
  models.Record:
    properties:
      difficult:
        minimum: 0
        type: integer
      onlineTotal:
        minimum: 0
        type: integer
      onlineWin:
        minimum: 0
        type: integer
      score:
        minimum: 0
        type: integer
      singleTotal:
        minimum: 0
        type: integer
      singleWin:
        minimum: 0
        type: integer
      time:
        type: number
    type: object
  models.Result:
    properties:
      message:
        type: string
      place:
        type: string
      success:
        type: boolean
    type: object
  models.UserPrivateInfo:
    properties:
      name:
        example: John
        maxLength: 30
        type: string
      password:
        example: easyPassword
        maxLength: 30
        minLength: 6
        type: string
    type: object
  models.UserPublicInfo:
    properties:
      bestScore:
        type: string
      bestTime:
        type: string
      difficult:
        type: integer
      id:
        type: integer
      name:
        maxLength: 30
        minLength: 3
        type: string
      photo:
        maxLength: 50
        type: string
    type: object
host: localhost:3001
info:
  contact: {}
  description: We don't have a public API, so instead of a real host(explosion.team)
    we specify localhost:3001. To test the following methods, git clone https://github.com/go-park-mail-ru/2019_1_Escapade,
    enter the root directory and run 'docker-compose up -d'
  license: {}
  title: Escapade Explosion API
  version: "1.0"
paths:
  /avatar:
    get:
      description: Get user avatar
      operationId: GetImage
      responses:
        "200":
          description: Avatar found successfully
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Required authorization
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: Avatar not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Get user avatar
    post:
      description: Create user avatar
      operationId: PostImage
      responses:
        "201":
          description: Avatar created successfully
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Required authorization
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: Avatar not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Create user avatar
  /game:
    post:
      consumes:
      - application/json
      description: Save offline game results
      operationId: OfflineSave
      parameters:
      - description: Results of offline game
        in: body
        name: record
        required: true
        schema:
          $ref: '#/definitions/models.Record'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Done
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: Wrong input data
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Required authorization
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: Avatar not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Save offline game
  /session:
    delete:
      description: logout
      operationId: Logout
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: logout
    post:
      description: login
      operationId: Login
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.UserPublicInfo'
        "400":
          description: invalid name or password
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: user not found
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: error with database
          schema:
            $ref: '#/definitions/models.Result'
      summary: login
  /user:
    delete:
      description: delete account
      operationId: DeleteAccount
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: invalid input
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: error with database
          schema:
            $ref: '#/definitions/models.Result'
      summary: delete account
    get:
      description: get public information about that user
      operationId: GetMyProfile
      parameters:
      - description: string enums
        enum:
        - A
        - B
        - C
        in: query
        name: enumstring
        type: string
      - description: int enums
        enum:
        - 1
        - 2
        - 3
        in: query
        name: enumint
        type: integer
      - description: int enums
        enum:
        - 1.1
        - 1.2
        - 1.3
        in: query
        name: enumnumber
        type: number
      - description: string valid
        in: query
        maxLength: 10
        minLength: 5
        name: string
        type: string
      - description: int valid
        in: query
        maximum: 10
        minimum: 1
        name: int
        type: integer
      - default: A
        description: string default
        in: query
        name: default
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Create user successfully
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: Invalid information
          schema:
            $ref: '#/definitions/models.Result'
      summary: get public information about that user
    post:
      consumes:
      - application/json
      description: create new user
      operationId: Register
      parameters:
      - description: User info1
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/models.UserPrivateInfo'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Create user successfully
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: Invalid information
          schema:
            $ref: '#/definitions/models.Result'
      summary: create new user
    put:
      description: update public info
      operationId: UpdateProfile
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Result'
        "400":
          description: invalid info
          schema:
            $ref: '#/definitions/models.Result'
        "401":
          description: need authorization
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: error with database
          schema:
            $ref: '#/definitions/models.Result'
      summary: update user information
  /users/{name}/profile:
    get:
      consumes:
      - application/json
      description: get user's best score and best time for a given difficulty, user's
        id, name and photo
      operationId: GetProfile
      parameters:
      - description: User name
        in: path
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Profile found successfully
          schema:
            $ref: '#/definitions/models.UserPublicInfo'
        "400":
          description: Invalid username
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/models.Result'
      summary: Get public user inforamtion
  /users/{page}:
    get:
      description: Get page of user list
      operationId: GetUsers
      responses:
        "200":
          description: Get successfully
          schema:
            items:
              $ref: '#/definitions/models.Result'
            type: array
        "400":
          description: Invalid pade
          schema:
            $ref: '#/definitions/models.Result'
        "404":
          description: Users not found
          schema:
            $ref: '#/definitions/models.Result'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: Get users list
  /users/pages_amount:
    get:
      description: Get amount of users list page
      operationId: GetUsersPageAmount
      responses:
        "200":
          description: Get successfully
          schema:
            $ref: '#/definitions/models.Pages'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/models.Result'
      summary: amount of users list page
swagger: "2.0"
